DotNest/Controllers/BookingController.cs
using DotNest.DataAccess.Entities;
using DotNest.Models;
using DotNest.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace DotNest.Controllers
{
    public class BookingController : Controller
    {
        private readonly IBookingService _bookingService;
        private readonly IRentalService _rentalService;
        private readonly ILocationService _locationService;
        private readonly IHttpContextAccessor _contextAccessor;


        public BookingController(
            IBookingService bookingService,
            IRentalService rentalService,
            IHttpContextAccessor contextAccessor,
            ILocationService locationService)
        {
            _bookingService = bookingService;
            _rentalService = rentalService;
            _contextAccessor = contextAccessor;
            _locationService = locationService;
        }

        public IActionResult Index()
        {
            string? username = _contextAccessor.HttpContext!.User.FindFirst(ClaimTypes.Name)?.Value;
            if (username is null)
                return RedirectToAction("Login", "User");

            List<BookingModel> bookings = _bookingService.GetAllBookingsFromUser(username!);
            return View(bookings);
        }

        public IActionResult Delete(int id)
        {
            string? username = _contextAccessor.HttpContext!.User.FindFirst(ClaimTypes.Name)?.Value;
            if (username is null)
                return RedirectToAction("Login", "User");

            _bookingService.DeleteBooking(id);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Book(int id)
        {
            string? username = _contextAccessor.HttpContext!.User.FindFirst(ClaimTypes.Name)?.Value;
            if (username is null)
                return RedirectToAction("Login", "User");

            ViewData["rentalId"] = id;
            RentalModel? rental = _rentalService.GetRental(id);

            if (rental is null)
            {
                return RedirectToAction("StatusCode", "Index", StatusCodes.Status404NotFound);
            }

            // Get the list of bookings of the rental
            List<BookingModel> bookings = _bookingService.GetBookingsByRentalId(id);

            List<string> unavailableDates = _locationService.GetUnavailableDates(bookings);

            ViewData["UnavailableDates"] = unavailableDates;
            ViewData["rentalName"] = rental.Name;

            return View();
        }

        [HttpPost]
        public IActionResult Book(BookingModel booking)
        {
            string? username = _contextAccessor.HttpContext!.User.FindFirst(ClaimTypes.Name)?.Value;
            if (username is null)
                return RedirectToAction("Login", "User");

            booking.Id = null; // The path param id corresponding to the rental id is wrongly assigned as the booking id, so we reset booking.Id
            if (!ModelState.IsValid)
                return View();

            ViewData["rentalId"] = booking.RentalId;
            ViewData["rentalName"] = booking.RentalName;

            // Get the list of bookings of the rental
            List<BookingModel> bookings = _bookingService.GetBookingsByRentalId(booking.RentalId);

            List<string> unavailableDates = _locationService.GetUnavailableDates(bookings);

            ViewData["UnavailableDates"] = unavailableDates;


            try
            {
                _bookingService.BookRental(username, booking);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("FromDate", ex.Message); // show an error message under the "from" field
                return View(booking); // show the view with the submitted info
            }
        }
    }
}

DotNest/Controllers/RentalController.cs
using DotNest.Models;
using DotNest.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Text.RegularExpressions;

namespace DotNest.Controllers
{
    [Authorize]
    public class RentalController : Controller
    {
        private readonly IHttpContextAccessor _contextAccessor;

        private readonly IRentalService _rentalService;

        private static readonly Regex CITY_REGEX = new Regex("((\\p{L})+[- ]?)+"); // accepts blocks of letters separated by a - or space 

        public RentalController(IHttpContextAccessor contextAccessor, IRentalService userService)
        {
            _contextAccessor = contextAccessor;
            _rentalService = userService;
        }



        // list of your rentals
        public IActionResult Index()
        {
            string? username = _contextAccessor.HttpContext!.User.FindFirst(ClaimTypes.Name)?.Value;
            if (username is null)
                return RedirectToAction("Login", "User");

            List<RentalItemListModel> rentals = _rentalService.GetAllRentalItemsOf(username!);

            return View(rentals);
        }

        public IActionResult Create()
        {
            string? username = _contextAccessor.HttpContext!.User.FindFirst(ClaimTypes.Name)?.Value;
            if (username is null)
                return RedirectToAction("Login", "User");

            return View();
        }

        [HttpPost]
        public IActionResult Create(RentalModel rental)
        {
            if (!ModelState.IsValid)
                return View();

            if (!CITY_REGEX.IsMatch(rental.City))
            {
                ModelState.AddModelError("City", "The city can only contain letters, - and spaces"); // show an error message under the username field
                return View(rental);
            }

            if (rental.Picture is null)
            {
                ModelState.AddModelError("Picture", "A picture must be added");
                return View(rental);
            }

            string? username = _contextAccessor.HttpContext!.User.FindFirst(ClaimTypes.Name)?.Value;
            if (username is null)
                return RedirectToAction("Login", "User");

            try
            {
                _rentalService.CreateRental(username, rental);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Name", ex.Message); // show an error message under the username field
                return View(rental); // show the view with the submitted info
            }
        }

        public IActionResult Update(int id)
        {
            string? username = _contextAccessor.HttpContext!.User.FindFirst(ClaimTypes.Name)?.Value;
            if (username is null)
                return RedirectToAction("Login", "User");

            RentalModel? rental = _rentalService.GetRental(id);

            if (rental is null)
                return RedirectToAction("Index", "StatusCode", StatusCodes.Status404NotFound);

            return View(rental);
        }

        [HttpPost]
        public IActionResult Update(int id, RentalModel rental)
        {
            string? username = _contextAccessor.HttpContext!.User.FindFirst(ClaimTypes.Name)?.Value;
            if (username is null)
                return RedirectToAction("Login", "User");

            if (!ModelState.IsValid)
                return View(rental);

            if (!CITY_REGEX.IsMatch(rental.City))
            {
                ModelState.AddModelError("City", "The city can only contain letters, - and spaces"); // show an error message under the username field
                return View(rental);
            }

            try
            {
                rental.Id = id;
                _rentalService.UpdateRental(rental);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Name", ex.Message); // show an error message under the username field
                return View(rental); // show the view with the submitted info
            }
        }
    }
}

DotNest/Controllers/Shared/StatusCodeController.cs
using Microsoft.AspNetCore.Mvc;

namespace DotNest.Controllers.Shared
{
    public class StatusCodeController : Controller
    {
        
        [HttpGet("/StatusCode/{statusCode}")]
        public IActionResult Index(int statusCode)
        {
            switch (statusCode)
            {
                case 404:
                    return View("404");
                case 500:
                    return View("500");
                default:
                    return View("Default");
            }
        }
        
    }
}

DotNest/Controllers/UserController.cs
using DotNest.Models;
using DotNest.Services.Interfaces;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace DotNest.Controllers
{
    public class UserController : Controller
    {
        private readonly IHttpContextAccessor _contextAccessor;

        private readonly IUserService _userService;

        public UserController(IHttpContextAccessor contextAccessor, IUserService userService)
        {
            _contextAccessor = contextAccessor;
            _userService = userService;
        }

        [Authorize]
        public ActionResult Index()
        { 
            return RedirectToAction("Index", "Location");
        }



        public ActionResult Register()
        {
            // check whether the user is already logged in
            string? username = _contextAccessor.HttpContext!.User.FindFirst(ClaimTypes.Name)?.Value;

            if (username is not null)
                return RedirectToAction("Index");


            // the user is not logged in, they can see the log in form
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(RegisterModel register)
        {
            // check whether the user is already logged in 
            string? username = _contextAccessor.HttpContext!.User.FindFirst(ClaimTypes.Name)?.Value;

            if (username is not null)
                return RedirectToAction("Index");


            // the user is not logged in, they can submit the form
            if (!ModelState.IsValid)
                return View(register);

            try
            {
                _userService.RegisterUser(register);

                // the user has created their account, they can now log in
                return RedirectToAction(nameof(Login));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Username", ex.Message); // show an error message under the username field
                return View(register); // show the view with the submitted info
            }

        }

        //GET
        public ActionResult Login()
        {
            // check whether the user is already logged in 
            string? username = _contextAccessor.HttpContext!.User.FindFirst(ClaimTypes.Name)?.Value;

            if (username is not null)
                return RedirectToAction("Index");

            // the user is not logged in, they can see the form
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginModel login)
        {
            // check whether the user is already logged in 
            string? username = _contextAccessor.HttpContext!.User.FindFirst(ClaimTypes.Name)?.Value;

            if (username is not null)
                return RedirectToAction("Index");


            // the user is not logged in, they can submit the form
            if (!ModelState.IsValid)
                return View(login);

            if (!_userService.ConfirmLoginValues(login))
            {
                ModelState.AddModelError("Username", "Invalid username or password");
                return View(login);
            }

            // add the user to the context
            var claims = new List<Claim> { new Claim(ClaimTypes.Name, login.Username) };
            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(claimsIdentity),
                new AuthenticationProperties()).Wait();

            return RedirectToAction(nameof(Index));
        }

        //POST
        [HttpPost]
        [Authorize]
        public ActionResult Logout()
        {
            HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme).Wait();

            return RedirectToAction(nameof(Login));
        }


    }
}

DotNest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DotNest.HMI</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DotNest.HMI.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/datepicker/css/bootstrap-datepicker.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Location" asp-action="Index">DotNest.HMI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Location" asp-action="Index">Accueil</a>
                        </li>
                        @if (User.Identity != null && User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Rental" asp-action="Index">Vos locations</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Booking" asp-action="Index">Vos réservations</a>
                            </li>
                        }
                    </ul>
                </div>
                @if (User.Identity != null && User.Identity.IsAuthenticated)
                {
                    <form asp-controller="User" asp-action="Logout" method="post" class="d-flex">
                        <button type="submit" class="btn btn-outline-danger">Déconnexion</button>
                    </form>
                }
                else
                {
                    <form asp-controller="User" asp-action="Login" method="get" class="d-flex">
                        <button type="submit" class="btn btn-outline-primary">Connexion</button>
                    </form>
                }
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - DotNest.HMI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
<script src="~/lib/momentjs/moment.min.js"></script>
<script src="~/lib/momentjs/locale/de-CH.js"></script>
<script src="~/lib/datepicker/js/tempusdominus-bootstrap-4.min.js"></script>
</html>